name: CI Coverage
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build & Test Backend
        run: mvn clean verify
      - name: Build & Test Frontend
        run: |
          cd front
          npm ci
          npm run test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/site/jacoco/index.html,./front/coverage/lcov.info,front/coverage/jest/lcov-report/index.html
          flags: unittests
          fail_ci_if_error: true

